---
title: "Las Vegas Trip (Gomi & Toto)"
output: 
  html_document:
    df_print: paged
    code_folding: "hide"
  pdf_document: default
runtime: shiny
---

# 

### Date: 12/14/2023 \~ 12/28/2023

### Location: 태성이형네 주소

**Day 1: 12/14/2023 - Welcome Day**

-   토토 할러데이 파티 끝나고 출발

-   밤에 도착

------------------------------------------------------------------------

**Day 2: 12/15/2023 - 장보기**

-   아침부터 2주치 장보기

-   오후에 할일 있음 하기

-   저녁은 Mott 32. 5:00 PM

-   저녁 후 플랜은 Go with the flow

------------------------------------------------------------------------

**Day 3: 12/16/2023 (Sat) - 자연 감상 데이**

-   Valley of the fire: 아침에 출발해서 점심 챙겨간거 먹고 (김밥같은거), 돌아옴. 1 way 1시간 거리

-   저녁은 쉬기 (TV 보던지, 할 일 있음 하던지)

------------------------------------------------------------------------

**Day 4: 12/17/2023 (Sun) - 교회데이**

-   오전에 예배를 Seed 하던지, Local 가던지. 그때 가서.

-   오후엔 휴식

------------------------------------------------------------------------

**Day 5: 12/18/2023 (Mon) - Sphere Day**

-   오전엔 일

-   오후에도 일

-   Sphere: 4:30 PM

------------------------------------------------------------------------

**Day 6: 12/19/2023 (Tue) - Valley of Fire Day**

-   **Day:** Venture out to **Valley of Fire State Park** for diverse scenic experiences.

-   **Evening:** Cook and enjoy a meal at your friend's house.

------------------------------------------------------------------------

**Day 7: 12/20/2023 (Wed) - Shopping Day**

-   **Day:** Shop at the **Las Vegas North Premium Outlets**.

-   **Evening:** Cook and enjoy a meal at your friend's house.

------------------------------------------------------------------------

**Day 8: 12/21/2023 (Thu) - Spa Day**

-   **Day:** Relax at **Canyon Ranch Spa** at The Venetian.

-   **Evening:** Cook and enjoy a meal at your friend's house.

------------------------------------------------------------------------

**Day 9: 12/22/2023 (Fri) - Adventure Day**

-   **Day:** Experience the **Voodoo Zip Line** at Rio.

-   **Evening:** Dine at **Mien Restaurant**, enjoying their variety of dishes.

------------------------------------------------------------------------

**Day 10: 12/23/2023 (Sat) - Exploration**

-   **Day:** Visit attractions or sites of your choice.

-   **Evening:** Cook and enjoy a meal at your friend's house.

------------------------------------------------------------------------

**Day 11: 12/24/2023 (Sun) - Christmas Eve**

-   **Day:** Enjoy the festive decorations around the city.

-   **Evening:** Cook and have a special Christmas Eve meal at your friend's house.

------------------------------------------------------------------------

**Day 12: 12/25/2023 (Mon) - Christmas Day**

-   **Evening:** Celebrate with a festive meal at **Scarpetta** at The Cosmopolitan, known for its Italian cuisine.

------------------------------------------------------------------------

**Day 13: 12/26/2023 (Tue) - Local Exploration**

-   **Day:** Discover local art galleries or attractions of your preference.

-   **Evening:** Cook and enjoy a meal at your friend's house.

------------------------------------------------------------------------

**Day 14: 12/27/2023 (Wed) - Fine Dining Night**

-   **Evening:** Relish the gourmet dishes at **Carbone** at ARIA Resort & Casino.

------------------------------------------------------------------------

**Day 15: 12/28/2023 (Thu) - Departure Day**

-   **Morning:** Pack, bid farewell, and depart.
